// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
export default function handler(req, res) {
  res.status(200).json({
    teams: [
      {
        name: 'The Europeans',
        primaryColor: 'eutpc',
        secondaryColor: 'eutsc',
        tertiaryColor: 'euttc',
        logo: '🇪🇺',
        wins: 0,
        members: [
          {
            firstName: 'Nick',
            lastName: 'Young',
            captain: true,
            image: 'nick.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'Bryan',
            lastName: 'Gregory',
            captain: false,
            image: 'bryan.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'Darin',
            lastName: 'Jennings',
            captain: false,
            image: 'darin.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'Jon',
            lastName: 'Sias',
            captain: false,
            image: 'jon.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'Joe',
            lastName: 'Voros',
            captain: false,
            image: 'joe.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'John',
            lastName: 'Young',
            captain: false,
            image: 'john.jpg',
            status: 'active',
            participation: ['2021'],
          },
        ],
      },
      {
        name: 'The Americans',
        primaryColor: 'ustpc',
        secondaryColor: 'ustsc',
        tertiaryColor: 'usttc',
        logo: '🇺🇸',
        wins: 1,
        members: [
          {
            firstName: 'Jeff',
            lastName: 'Hansen',
            captain: true,
            image: 'jeff.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'Tim',
            lastName: 'Bates',
            captain: false,
            image: 'tim.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'Mark',
            lastName: 'Gauer',
            captain: false,
            image: 'mark.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'Garrett',
            lastName: 'Ormsb',
            captain: false,
            image: 'garrett.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'Nate',
            lastName: 'Stair',
            captain: false,
            image: 'nate.jpg',
            status: 'active',
            participation: ['2021'],
          },
          {
            firstName: 'Matt',
            lastName: 'Young',
            captain: false,
            image: 'matt.jpg',
            status: 'active',
            participation: ['2021'],
          },
        ],
      },
    ],
  });
}
